name: Weather

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
      npm install
      npm run formatting:check
      npm run build

    - uses: actions/upload-artifact@master
      with:
        name: weather
        path: release/