name: Weather

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: npm install
    - run: npm run formatting:check
    - run: npm run build
    - run: npm test

    - uses: actions/upload-artifact@master
      with:
        name: weather
        path: release/